More better now
Marjani/Google-Translator pull request #1
Opened 2017-03-24 17:39 UTC by landlogicit

More better now

2017-03-28 08:58 UTC, Marjani requested changes

2017-03-28 08:58 UTC, Marjani commented on Marjani.Net.Utility/Translator.cs
> +            TargetLanguage = "Italian";
Please return to "Persian"

2019-11-23 10:18 UTC, landlogicit commented on Marjani.Net.Utility/Translator.cs
> +            TargetLanguage = "Italian";
revert to persian

2019-11-23 10:31 UTC, landlogicit commented
revert to persian

2019-11-23 15:49 UTC, merged